Better checking of first parameter

diff --git a/mkvcleaner b/mkvcleaner
--- a/mkvcleaner
+++ b/mkvcleaner
@@ -14,8 +14,8 @@ MKVMERGE=$(which mkvmerge)
 FIND=$(which find)
 
 # Require path as argument
-if ! test -d $1; then
-    echo 'Missing DIRECTORY parameter' >&2
+if ! test -d "$1"; then
+    echo 'Missing or invalid DIRECTORY parameter' >&2
     exit 1
 fi
 
